language: haskell
install:
  - git clone https://github.com/elm-lang/Elm.git
  - cabal sandbox init
  - cabal sandbox add-source Elm
script: cabal configure --enable-tests && cabal build && cabal test
